# fly.toml app configuration file generated for green-meadow-159 on 2023-09-17T19:38:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-meadow-159"
primary_region = "ams"

[build]

[http_service]
  internal_port = 7777
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
