# fly.toml app configuration file generated for wg-recipes on 2023-11-30T18:42:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wg-recipes"
primary_region = "ams"

[build]

[http_service]
  internal_port = 7777
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
